
steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/plant-disease-mlops/docker_img', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/plant-disease-mlops/docker_img']
