# Base image
FROM python:3.10-slim-buster

# install python
RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc curl && \
    apt clean && rm -rf /var/lib/apt/lists/*

# install Google Cloud SDK
RUN curl https://sdk.cloud.google.com > install.sh
RUN bash install.sh --disable-prompts
# changing RUN commando to run bash instead of sh
SHELL ["/bin/bash", "-c"]
COPY DATA_KEY_FILE.json DATA_KEY_FILE.json
RUN /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=DATA_KEY_FILE.json
RUN /root/google-cloud-sdk/bin/gsutil cp -r gs://plant-disease-mlops-data-bucket .

# Fixing data location
RUN mv plant-disease-mlops-data-bucket/data data
RUN rm -r plant-disease-mlops-data-bucket

# copy setup and installation files
COPY src/configs src/configs
COPY requirements.txt requirements.txt
COPY setup.py setup.py

# copy model training files
COPY src/data/dataloader.py src/data/dataloader.py
COPY src/models/model.py src/models/model.py
COPY src/models/train_model.py src/models/train_model.py

WORKDIR /
RUN pip install -r requirements.txt --no-cache-dir
RUN pip3 install torch torchvision torchaudio
