wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673482529.534436
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.10.8
      5: 0.13.8
      8:
      - 5
experiment.training.lr:
  desc: null
  value: 0.05984504390226501
