program: src/models/train_model.py
method: bayes
metric:
  name: val_loss
  goal: minimize
run_cap: 100
parameters:
  experiment.training.lr:
    distribution: log_uniform
    min: -11.512925465
    max: -2.30258509299
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
