program: src/models/train_model.py
method: grid
metric:
  name: val_loss
  goal: minimize
run_cap: 1
parameters:
  experiment.training.lr:
    distribution: constant
    value: 0.0035900486014863666
  experiment.training.batch_size:
    distribution: constant
    value: 100
  experiment.training.epochs:
    distribution: constant
    value: 100
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
