program: src/models/train_model.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  experiment.training.lr:
    min: 0.0001
    max: 0.1
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
